services:
  product-local-database:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: product-local-database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: welcome
    ports:
      - "3306:3306"
    volumes:
      - ./src/main/resources/db/container/database:/docker-entrypoint-initdb.d
    command:
      - --default-time-zone=Asia/Seoul
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --character-set-client-handshake=0
      - --slow-query-log=ON
      - --long-query-time=2
  product-local-redis:
    platform: linux/x86_64
    image: redis
    ports:
      - "6379:6379"
    container_name: product-local-redis
    restart: always
  product-local-s3:
    platform: linux/x86_64
    image: localstack/localstack
    ports:
      - "4566:4566" # LocalStack의 기본 포트
    environment:
      - SERVICES=s3
      - DEBUG=1
    container_name: product-local-s3
    restart: always
    volumes:
      - "./localstack:/data/localstack/data"
      - "./localstack-init:/docker-entrypoint-initaws.d" # 초기화 스크립트 디렉터리